resourcePackages:
- org.icreated.wstore.endpoints
prettyPrint: true
cacheTTL: 0

openAPI:
  servers:
    - url: http://localhost:8080/services/api
    - url: http://3.104.36.71:8080/services/api
  components:
    securitySchemes:
      bearerAuth:
        type: http
        scheme: bearer
        bearerFormat: JWT
        
  security:
  - bearerAuth: []
  
  info:
    version: '3.0'
    title: WebStore API
    description: 'Web Services Idempiere Webstore API'
    termsOfService: http://www.idempiere.org
    contact: 
      email: contact.icreated@gmail.com
    license:
      name: Apache
      url: http://www.apache.org/licenses/LICENSE-2.0.html
  

